spring:


  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:classicmodels}
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
    #    driver-class-name: org.postgresql.Driver


    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
