spring:


  datasource:
    url: jdbc:mysql://localhost:5432/classicmodelsV2
    username: mysql
    password: Cmwende@3
    #    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.mySQLDialect
server:
  port: 8081
