#spring:
#
#
#  datasource:
#    url: ${DB_URL:jdbc:mysql://localhost:3306/classicmodelsV2}
#    username: ${DB_USERNAME:root}
#    password: ${DB_PASSWORD:defaultpassword}
#    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
#
#
#    hikari:
#      connection-timeout: 30000
#      maximum-pool-size: 10
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: ${DATABASE:mysql}
#    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
#server:
#  port: ${SERVER_PORT:8080}
#
#
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT}